all:
	gcc -o producer_consumer  producer_consumer.c
	gcc -o read_write Read_Write.c
	gcc -o thread_mutex thread_mutex.c
	gcc -o thread_pid thread_pid.c
clean:
	rm -rf producer_consumer read_write thread_mutex thread_pid